return {
  "catppuccin/nvim",
  name = "catppuccin",
  lazy = false,
  priority = 100,
  config = function()
    require("catppuccin").setup({
      flavour = "latte",
      color_overrides = {
        latte = {
          rosewater = "#da1e28",
          flamingo = "#da1e28",
          red = "#da1e28",
          maroon = "#da1e28",
          pink = "#d02670",
          mauve = "#8a3ffc",
          peach = "#d44a1c",
          yellow = "#ab8600",
          green = "#007d79",
          teal = "#1192e8",
          sky = "#1192e8",
          sapphire = "#1192e8",
          blue = "#0f62fe",
          lavender = "#0f62fe",
          text = "#000000",
          subtext1 = "#404040",
          subtext0 = "#474747",
          overlay2 = "#575757",
          overlay1 = "#595959",
          overlay0 = "#737373",
          surface2 = "#8c8c8c",
          surface1 = "#d1d1d1",
          surface0 = "#e6e6e6",
          base = "#FFFFFF",
          mantle = "#f2f2f2",
          crust = "#ebebeb",
        },
      },
      styles = {
        comments = { "italic" },
        conditionals = { "italic" },
        functions = { "italic" },
        keywords = { "italic" },
        numbers = { "bold" },
        types = { "bold" },
      },
      integrations = {
        notify = true,
        lsp_trouble = true,
        dashboard = false,
        hop = true,
        nvimtree = false,
        native_lsp = {
          enabled = true,
          virtual_text = {
            errors = { "italic" },
            hints = { "italic" },
            warnings = { "italic" },
            information = { "italic" },
          },
          underlines = {
            errors = { "undercurl" },
            hints = { "undercurl" },
            warnings = { "undercurl" },
            information = { "undercurl" },
          },
        },
      },
      highlight_overrides = {
        all = function(colors)
          return {
            NormalFloat = { bg = colors.mantle },
            FloatBorder = { bg = colors.mantle, fg = colors.mantle },
            CursorLineNr = { fg = colors.mauve, style = { "bold" } },
            PmenuSel = { bg = colors.surface0, fg = "" },
            Pmenu = { bg = colors.mantle },
            PmenuSbar = { bg = colors.crust },
            PmenuThumb = { bg = colors.surface0 },
            VertSplit = { fg = colors.base },

            TelescopeSelection = { bg = colors.surface0 },
            TelescopePromptCounter = { fg = colors.mauve, style = { "bold" } },

            TelescopePromptPrefix = { bg = colors.surface0 },
            TelescopePromptNormal = { bg = colors.surface0 },
            TelescopeResultsNormal = { bg = colors.mantle },
            TelescopePreviewNormal = { bg = colors.crust },

            TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
            TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
            TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },

            TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
            TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
            TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },

            GitSignsChange = { fg = colors.peach },
            GitSignsCurrentLineBlame = { link = "Comment" },

            IndentBlanklineChar = { fg = colors.surface0 },
            IndentBlanklineContextChar = { fg = colors.surface2 },

            NoiceConfirm = { bg = colors.mantle, fg = colors.mauve },
            NoiceCmdlineIconLua = { fg = colors.blue },
            NoiceConfirmBorder = { bg = colors.mantle, fg = colors.mantle },
            NoiceMini = { link = "Comment" },
            NoiceLspProgressClient = { fg = colors.blue, style = { "italic", "bold" } },

            NeoTreeNormal = { bg = colors.mantle },
            NeoTreeRootName = { fg = colors.blue, style = { "bold" } },
            NeoTreeNormalNC = { bg = colors.mantle },
            NeoTreeFloatBorder = { link = "FloatBorder" },
            NeoTreeTabActive = { fg = colors.text, bg = colors.mantle },
            NeoTreeTabSeparatorActive = { fg = colors.mantle, bg = colors.mantle },
            NeoTreeTabInactive = { fg = colors.surface2, bg = colors.crust },
            NeoTreeTabSeparatorInactive = { fg = colors.crust, bg = colors.crust },
            NeoTreeWinSeparator = { fg = colors.base, bg = colors.base },
            NeoTreeGitConflict = { fg = colors.red },
            NeoTreeGitDeleted = { fg = colors.red },
            NeoTreeGitIgnored = { fg = colors.overlay0 },
            NeoTreeGitModified = { fg = colors.peach },
            NeoTreeGitUnstaged = { fg = colors.red },
            NeoTreeGitUntracked = { fg = colors.blue },
            NeoTreeGitStaged = { fg = colors.green },
            -- carbon
            Structure = { fg = colors.pink },
            StorageClass = { fg = colors.pink },
            Type = { fg = colors.pink, style = { "bold" } },
            Constant = { fg = colors.text, style = { "bold" } },
            Number = { fg = colors.text },
            Float = { fg = colors.text },
            Boolean = { fg = colors.pink },
            ["@function.builtin"] = { fg = colors.pink },
            ["@method"] = { fg = colors.pink },
            ["@constant"] = { fg = colors.text, style = { "bold" } },
            ["@variable.builtin"] = { fg = colors.pink },
            ["@type.builtin"] = { fg = colors.pink, style = { "bold" } },
          }
        end,
      },
    })

    vim.api.nvim_command("colorscheme catppuccin")
  end,
}
