#!/usr/bin/env bash
file=$1
w=$(($2 - 1))
h=$(($3 - 1))
x=$4
y=$(($5 + 1))

filetype="$(file -Lb --mime-type "$file")"

if [[ "$filetype" =~ ^image ]]; then
	echo "Size: $(exiftool "$1" | grep '^Image Size' | awk '{print $4}')"
	kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
	exit 1
fi

if [[ "$filetype" =~ ^video ]]; then
	echo "Duration: $(exiftool "$1" | grep '^Duration' | awk '{print $3}')"
	# vidthumb is from here:
	# https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
	kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(vidthumb "$file")"
	exit 1
fi

stpv "$file"
