local theme = {}

local themes = {
	light = {
		rosewater = "#c14a4a",
		flamingo = "#c14a4a",
		pink = "#945e80",
		mauve = "#945e80",
		red = "#c14a4a",
		maroon = "#c14a4a",
		peach = "#c35e0a",
		yellow = "#a96b2c",
		green = "#6c782e",
		teal = "#4c7a5d",
		sky = "#4c7a5d",
		sapphire = "#4c7a5d",
		blue = "#45707a",
		lavender = "#45707a",
		text = "#654735",
		subtext1 = "#7b5d44",
		subtext0 = "#8f6f56",
		overlay2 = "#a28368",
		overlay1 = "#b6977a",
		overlay0 = "#c9aa8c",
		surface2 = "#A79C86",
		surface1 = "#C9C19F",
		surface0 = "#DFD6B1",
		base = "#fbf1c7",
		mantle = "#F3EAC1",
		crust = "#E7DEB7",
	},
	dark = {
		rosewater = "#EA6962",
		flamingo = "#EA6962",
		pink = "#D3869B",
		mauve = "#D3869B",
		red = "#EA6962",
		maroon = "#EA6962",
		peach = "#BD6F3E",
		yellow = "#D8A657",
		green = "#A9B665",
		teal = "#89B482",
		sky = "#89B482",
		sapphire = "#89B482",
		blue = "#7DAEA3",
		lavender = "#7DAEA3",
		text = "#D4BE98",
		subtext1 = "#BDAE8B",
		subtext0 = "#A69372",
		overlay2 = "#5A5E60",
		overlay1 = "#55595B",
		overlay0 = "#5F6365",
		surface2 = "#4B4F51",
		surface1 = "#3c3f40",
		surface0 = "#2d2f30",
		base = "#1D2021",
		mantle = "#191C1D",
		crust = "#151819",
	},
}

theme.palette = themes.dark

function theme.setup(config)
	config.colors = {
		split = theme.palette.base,
		foreground = theme.palette.text,
		background = theme.palette.base,
		cursor_bg = theme.palette.overlay0,
		cursor_border = theme.palette.overlay0,
		cursor_fg = theme.palette.base,
		selection_bg = theme.palette.surface2,
		selection_fg = theme.palette.text,
		visual_bell = theme.palette.surface0,
		indexed = {
			[16] = theme.palette.peach,
			[17] = theme.palette.rosewater,
		},
		scrollbar_thumb = theme.palette.surface2,
		compose_cursor = theme.palette.flamingo,
		ansi = {
			theme.palette.surface0,
			theme.palette.red,
			theme.palette.green,
			theme.palette.yellow,
			theme.palette.blue,
			theme.palette.mauve,
			theme.palette.teal,
			theme.palette.text,
		},
		brights = {
			theme.palette.surface2,
			theme.palette.red,
			theme.palette.green,
			theme.palette.yellow,
			theme.palette.blue,
			theme.palette.mauve,
			theme.palette.teal,
			theme.palette.surface2,
		},
		tab_bar = {
			background = theme.palette.mantle,
			active_tab = {
				bg_color = "none",
				fg_color = theme.palette.subtext1,
				intensity = "Bold",
				italic = true,
			},
			inactive_tab = {
				bg_color = theme.palette.mantle,
				fg_color = theme.palette.surface2,
			},
			inactive_tab_hover = {
				bg_color = theme.palette.mantle,
				fg_color = theme.palette.surface2,
			},
			new_tab = {
				bg_color = theme.palette.mantle,
				fg_color = theme.palette.subtext0,
			},
			new_tab_hover = {
				bg_color = theme.palette.mantle,
				fg_color = theme.palette.surface2,
			},
		},
	}
end

return theme
